# Generated by Django 4.2.30 on 2026-09-23 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_departamento_cargo_empleado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usuariorol',
            name='id_rol',
        ),
        migrations.RemoveField(
            model_name='usuariorol',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='empleado',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='usuarios.persona'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='UsuarioRol',
        ),
    ]
