# Generated by Django 4.2.30 on 2026-09-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuariorol_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='id_rol',
            field=models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='usuarios.rol'),
        ),
    ]
